---
- name: Stop Nginx
  hosts: all
  become: yes
  tasks:
    - name: Uninstall nginx
      apt:
        name: nginx
        state: absent
    - name: Stop nginx
      service:
        name: nginx
        state: stopped
